Parse
kalgory-com/kalgory-py pull request #9
Opened 2024-07-15 10:06 UTC by ChuWeiChang

Completion of user library. I will look into publishing it on pypl tonight.
It is a little troublesome to modify guest.py automatically in testing stage, so I tried to make it more complicated.

In python, list and tuple is really confusing, so I only make a simple check on the two data structures. I look to make it more complete in the future by issuing a reminder.

2024-07-15 14:37 UTC, ZhaoTzuHsien commented on tests/test_kalgory.py
> +            data = {"o1": 1, "o2": 20010714.0, "o3": (123, "fefe")}
The testing data should be the following for good
```json
[1, 20010714.0, [123, "fefe"]]
```

2024-07-15 14:42 UTC, ZhaoTzuHsien commented
I think there are some misunderstandings when I was reviewing your code.

According to #6, the payload format is a JSON array. Each of its items in the array is a parameter to the user handle function. You can review the issue #6 thoroughly to see complete implementation guidance. If you have any question about the payload format or implementation problem, feel free to ask any question.

@ChuWeiChang

2024-07-15 14:44 UTC, ZhaoTzuHsien requested changes
Rewrite of the implementation that follows #6 is required.

2024-07-16 05:37 UTC, ChuWeiChang commented on tests/test_kalgory.py
> +            data = {"o1": 1, "o2": 20010714.0, "o3": (123, "fefe")}
i understand what you trying to say, but what do you mean "for good "

2024-07-16 08:43 UTC, ZhaoTzuHsien approved these changes
LGTM. Can be merged now.

2024-07-16 08:45 UTC, merged